### ISSUE TITLE
question: does this nvidia driver work with the latest stable flatcar kenerl (5.15)?

### ISSUE THREAD

**Issue by AnalogJ** [jepio/flatcar-nvidia-overlay#1]
I've been trying to compile the Nvidia driver from source on a Flatcar development container. 
Recently it began failing consistently with errors like:

```
     CC [M]  /tmp/nvidia/NVIDIA-Linux-x86_64-460.32.03/kernel/nvidia/nv-frontend.o
     CC [M]  /tmp/nvidia/NVIDIA-Linux-x86_64-460.32.03/kernel/nvidia/nv.o
   In file included from ./include/linux/kernel.h:5,
                    from ./include/linux/list.h:9,
                    from ./include/linux/preempt.h:11,
                    from ./include/linux/spinlock.h:55,
                    from /tmp/nvidia/NVIDIA-Linux-x86_64-460.32.03/kernel/common/inc/nv-lock.h:16,
                    from /tmp/nvidia/NVIDIA-Linux-x86_64-460.32.03/kernel/common/inc/nv-linux.h:20,
                    from /tmp/nvidia/NVIDIA-Linux-x86_64-460.32.03/kernel/nvidia/nv-frontend.c:13:
   ./include/linux/stdarg.h:6: warning: "va_start" redefined
       6 | #define va_start(v, l) __builtin_va_start(v, l)
```

I was able to fix the complication by using an older driver & a fix released by `if-not-true-then-false.com`: https://www.if-not-true-then-false.com/2020/inttf-nvidia-patcher/

https://github.com/mediadepot/docker-flatcar-nvidia-driver/blob/master/compile-patched.sh#L11-L16

The problem is that, while compilation finishes successfully, I cannot `depmod` or `modprobe` the compiled kernel modules:

```
Apr 13 06:20:44 localhost bash[570434]: depmod: ERROR: openat(//lib/modules/5.15.32-flatcar, modules.dep.570434.941891.1649830844, 301, 644): Read-only file system
Apr 13 06:20:44 localhost bash[570434]: depmod: ERROR: openat(//lib/modules/5.15.32-flatcar, modules.dep.bin.570434.941891.1649830844, 301, 644): Read-only file system
Apr 13 06:20:44 localhost bash[570434]: depmod: ERROR: openat(//lib/modules/5.15.32-flatcar, modules.alias.570434.941891.1649830844, 301, 644): Read-only file system
Apr 13 06:20:44 localhost bash[570434]: depmod: ERROR: openat(//lib/modules/5.15.32-flatcar, modules.alias.bin.570434.941891.1649830844, 301, 644): Read-only file system
Apr 13 06:20:44 localhost bash[570434]: depmod: ERROR: openat(//lib/modules/5.15.32-flatcar, modules.softdep.570434.941891.1649830844, 301, 644): Read-only file system
Apr 13 06:20:44 localhost bash[570434]: depmod: ERROR: openat(//lib/modules/5.15.32-flatcar, modules.symbols.570434.941891.1649830844, 301, 644): Read-only file system
Apr 13 06:20:44 localhost bash[570434]: depmod: ERROR: openat(//lib/modules/5.15.32-flatcar, modules.symbols.bin.570434.941891.1649830844, 301, 644): Read-only file system
Apr 13 06:20:44 localhost bash[570434]: depmod: ERROR: openat(//lib/modules/5.15.32-flatcar, modules.builtin.bin.570434.941891.1649830844, 301, 644): Read-only file system
Apr 13 06:20:44 localhost bash[570434]: depmod: ERROR: openat(//lib/modules/5.15.32-flatcar, modules.builtin.alias.bin.570434.941891.1649830844, 301, 644): Read-only file system
Apr 13 06:20:44 localhost bash[570434]: depmod: ERROR: openat(//lib/modules/5.15.32-flatcar, modules.devname.570434.941891.1649830844, 301, 644): Read-only file system
Apr 13 06:20:44 localhost bash[570000]: ++ modprobe -d / ipmi_devintf
Apr 13 06:20:44 localhost bash[570000]: ++ depmod -b /opt/drivers/nvidia
Apr 13 06:20:44 localhost bash[570480]: depmod: WARNING: could not open modules.order at /opt/drivers/nvidia/lib/modules/5.15.32-flatcar: No such file or directory
Apr 13 06:20:44 localhost bash[570480]: depmod: WARNING: could not open modules.builtin at /opt/drivers/nvidia/lib/modules/5.15.32-flatcar: No such file or directory
Apr 13 06:20:44 localhost bash[570000]: ++ modprobe -d /opt/drivers/nvidia nvidia
Apr 13 06:20:45 localhost bash[570481]: modprobe: ERROR: could not insert 'nvidia': Exec format error
Apr 13 06:20:45 localhost systemd[1]: Finished Compile Kernel Modules for Flatcar.
```

Is this an issue you've run into?

**Comment by jepio** [comment]
Hi @AnalogJ,
I was just looking into our Nvidia driver situation, and found this blog post of yours https://blog.thesparktree.com/customize-flatcar-kernel-part-3. I was planning to reach out to work together to improve the situation.

Right now I'm testing on Flatcar beta images with kernel 5.15.32. Everything works with driver version 510.47.03, 470.103.01 and 460.106.00. Any particular reason you chose 460.32.03?

Just to make sure - you're on amd64 right?

**Comment by jepio** [comment]
I also get the "exec format error" when using the workflow from https://github.com/mediadepot/docker-flatcar-nvidia-driver/. dmesg says:
```
[ 4371.717507] module: x86/modules: Skipping invalid relocation target, existing value is nonzero for type 1, loc 00000000edc6d5de, val ffffffffc1771873
```

Here's a fix that let's me modprobe the module correctly (i'm testing with NVIDIA_DRIVER_VERSION=470.103.01 and FLATCAR_VERSION=3185.1.0`:

```patch
diff --git a/Dockerfile b/Dockerfile
index b14f53e..2fedbaa 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,15 +1,15 @@
 ARG FLATCAR_VERSION
 ARG NVIDIA_DRIVER_VERSION
 
-FROM mediadepot/flatcar-developer:${FLATCAR_VERSION}-sources as BUILD
+FROM mediadepot/flatcar-developer:${FLATCAR_VERSION} as BUILD
 LABEL maintainer="Jason Kulatunga <jason@thesparktree.com>"
 
 ARG FLATCAR_VERSION
 ARG NVIDIA_DRIVER_VERSION
 
 WORKDIR /tmp
-#COPY compile.sh /compile.sh
-COPY compile-patched.sh /compile.sh
+COPY compile.sh /compile.sh
+#COPY compile-patched.sh /compile.sh
 COPY install.sh /install.sh
 RUN /compile.sh
 
diff --git a/compile.sh b/compile.sh
index 5b0e610..c356b39 100755
--- a/compile.sh
+++ b/compile.sh
@@ -13,7 +13,6 @@ export KERNEL_VERSION=$(cat /usr/src/linux/include/config/kernel.release || ls /
 # see https://github.com/NVIDIA/nvidia-installer/blob/eef089de55aeabe537c67a17e1f71db99aa23be6/option_table.h for a full list of options/flags
 ./nvidia-installer -s -n \
   --kernel-name="${KERNEL_VERSION}" \
-  --kernel-source-path=/usr/src/linux \
   --no-check-for-alternate-installs \
   --no-opengl-files \
   --no-distro-scripts \
```
the stock developer container has enough of kernel devel installed that modules can be built against /lib/modules/5.15.x-flatcar, if you skip `--kernel-source-path` the nvidia-installer uses those paths. That way you can also skip the `emerge coreos-sources` step.

The depmod issue might be because recently `/usr/lib` and `/usr/lib64` stopped being symlinks to each-other (https://github.com/flatcar-linux/coreos-overlay/pull/1713). We tried to keep as many compat symlinks as possible, but it needed to be done for systemd compatibility, sorry for that. Might this cause issues with your overlay? The canonical path for kernel module installation is (/usr)/lib/modules.

**Comment by jepio** [comment]
I'll investigate why building against `coreos-sources` would fail.

**Comment by AnalogJ** [comment]
awesome, thanks for the help @jepio  that worked! 
I also created a writable overlay for the /usr/lib64 dir as mentioned in the Flatcar documentation. It's been codified here:
https://github.com/mediadepot/flatcar-forklift/blob/master/usr-lib64-modules.mount

With those changes, I am now able to successfully run `nvidia-smi` on my flatcar server. Thanks!!

**Comment by jepio** [comment]
I think I found the reason that it doesn't work when building against /usr/src/linux: the developer container is missing pahole, and without it the modules_prepare modifies the .config in a way that affects the built nvidia kernel modules. We'll be adding pahole into the developer container to prevent this. Thanks for bringing this to my attention!

**Comment by AnalogJ** [comment]
thanks for figuring this out @jepio
